//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Plane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plane()
        {
            this.Flight = new HashSet<Flight>();
        }

        public string ImageBin { get { return Directory.GetCurrentDirectory().Substring(0 ,Directory.GetCurrentDirectory().Length - 9) + "/Resources/Plane/" + Image; } }
        public string NameBin { get { return Name;  } }
        public string SpeedBin { get { return Speed.ToString(); } }

        public int ID_plane { get; set; }
        public string type { get; set; }
        public int Number_of_workers { get; set; }
        public int Number_of_pilots { get; set; }
        public int Number_of_seats { get; set; } 
        public string Name { get; set; }
        public int Speed { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
