//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID_ticket { get; set; }
        public int ID_Flight { get; set; }
        public int ID_buyer { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
